name: Build - Master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: microsoft/vscode-dev-containers:ubuntu

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test