name: Test VS Code Minimum (1.90.0)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-minimum:
    name: Test on ${{ matrix.os }} with VS Code 1.90.0
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache node modules
        uses: actions/cache@v4
        id: cache-npm
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json', '**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true'}}
        name: List the state of node modules
        continue-on-error: true
        run: npm list
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Run tests with VS Code 1.90.0
        uses: coactions/setup-xvfb@v1
        with:
          run: npm test
        env:
          VSCODE_VERSION: '1.90.0'