name: Test VS Code Minimum (1.90.0)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-minimum:
    name: Test on ${{ matrix.os }} with VS Code 1.90.0
    timeout-minutes: 3
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Cache dependencies
        uses: actions/cache@v4
        id: cache-deps
        with:
          path: |
            ~/.npm
            node_modules
          key: deps-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            deps-${{ runner.os }}-
            deps-
      - if: ${{ steps.cache-deps.outputs.cache-hit != 'true'}}
        name: List the state of node modules
        continue-on-error: true
        run: npm list
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Run tests with VS Code 1.90.0 and rate limit handling
        uses: coactions/setup-xvfb@v1
        with:
          run: |
            # Add delay to handle Toptal API rate limiting (30 req/min)
            echo "Waiting 25 seconds before running tests to avoid rate limiting..."
            sleep 25
            npm test
        env:
          VSCODE_VERSION: '1.90.0'
          # Rate limiting configuration
          TEST_DELAY_MS: 2000
          MAX_RETRIES: 3
        timeout-minutes: 2